# Copyright (c) 2017-present SIGHUP s.r.l All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configurations:
  - kustomize-config.yml

commonLabels:
  app: pomerium

namespace: pomerium

resources:
  - namespace.yml
  - deploy.yml
  - svc.yml
  - ingress.yml
  - monitoring

secretGenerator:
  - name: pomerium-env
    envs:
      - secrets/pomerium.example.env

configMapGenerator:
  - name: pomerium-policy
    files:
      - policy.yml=config/policy.example.yaml
  - name: pomerium
    envs:
      - config/config.example.env

vars:
  - name: AUTHENTICATE_SERVICE_HOST
    objref:
      kind: ConfigMap
      name: pomerium
      apiVersion: v1
    fieldref:
      fieldpath: data.AUTHENTICATE_SERVICE_HOST
  - name: FORWARD_AUTH_HOST
    objref:
      kind: ConfigMap
      name: pomerium
      apiVersion: v1
    fieldref:
      fieldpath: data.FORWARD_AUTH_HOST

images:
  - name: pomerium/pomerium
    newName: registry.sighup.io/fury/pomerium/pomerium
    newTag: nonroot-v0.27.1
